# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
    jmx:
        enabled: false
    main:
        banner-mode: OFF

    lifecycle:
        timeout-per-shutdown-phase: 20s

    # ====================================================================================================================
    # = DATA SOURCE
    # ====================================================================================================================
    datasource:
        url: jdbc:mariadb://localhost:3306/todo_db
        driver-class-name: org.mariadb.jdbc.Driver
        username: todo_usr
        password: todo_pwd
        hikari:
            poolName: hikari-pool-todo

    # ====================================================================================================================
    # = JPA
    # ====================================================================================================================
    jpa:
        open-in-view: false
        properties:
            hbm2ddl:
                auto: validate

            # ================================================================================================================
            # = HIBERNATE
            # ================================================================================================================
            hibernate:
                show_sql: false
                use_sql_comments: false
                format_sql: false
                jdbc:
                    time_zone: Europe/Amsterdam
                    use_get_generated_keys: true
                    lob:
                        non_contextual_creation: true

    # ====================================================================================================================
    # = JACKSON
    # ====================================================================================================================
    jackson:
        mapper:
            ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
        time-zone: Europe/Amsterdam

    # ====================================================================================================================
    # = MAIL
    # ====================================================================================================================
    mail:
        host: 127.0.0.1
        port: 1025

    # ====================================================================================================================
    # = WEB
    # ====================================================================================================================
    web:
        locale: nl

# ======================================================================================================================
# = WEB SERVER
# ======================================================================================================================
server:
    servlet:
        context-path: /api
    shutdown: graceful
    # ==================================================================================================================
    # = SERVER - INCLUDE AN ERROR MESSAGE JSON
    # ==================================================================================================================
    error:
        include-message: always

# ======================================================================================================================
# = OPEN API
# ======================================================================================================================
springdoc:
    swagger-ui:
        path: /v3/swagger-ui.html

# ======================================================================================================================
# = ACTUATOR - ALL METRICS OVER HTTP INSTEAD OF JMX
# ======================================================================================================================
management:
    endpoints:
        jmx:
            exposure:
                exclude: '*'
        web:
            exposure:
                include: '*'

# ======================================================================================================================
# = LOGGING
# ======================================================================================================================
logging:
    pattern:
        console: '%date [%thread] %-5level %logger\(%mdc{IP}\) - [%mdc{RID}] %message%n'
    level:
        root: INFO
        org:
            springframework:
                security:
                    web:
                        csrf: DEBUG
                transaction:
                    interceptor: TRACE
                aop:
                    interceptor: TRACE
        com:
            github:
                ronlievens: TRACE
